#!/usr/bin/env python3

MODULE_ALIASES = {
    "plenoptic": "po",
    "simulate": "simul",
    "synthesize": "synth",
}

# dictionary with old  API to new API
API_CHANGE = {
    "plenoptic.synthesize.metamer.Metamer": "plenoptic.Metamer",
    "plenoptic.synthesize.Metamer": "plenoptic.Metamer",
    "plenoptic.synthesize.metamer.MetamerCTF": "plenoptic.MetamerCTF",
    "plenoptic.synthesize.MetamerCTF": "plenoptic.MetamerCTF",
    "plenoptic.synthesize.eigendistortion.Eigendistortion": "plenoptic.Eigendistortion",
    "plenoptic.synthesize.Eigendistortion": "plenoptic.Eigendistortion",
    "plenoptic.synthesize.mad_competition.MADCompetition": "plenoptic.MADCompetition",
    "plenoptic.synthesize.MADCompetition": "plenoptic.MADCompetition",
    "plenoptic.simulate.models.portilla_simoncelli.PortillaSimoncelli": "plenoptic.models.PortillaSimoncelli",
    "plenoptic.simulate.PortillaSimoncelli": "plenoptic.models.PortillaSimoncelli",
    "plenoptic.simulate.models.frontend.LinearNonlinear": "plenoptic.models.LinearNonlinear",
    "plenoptic.simulate.LinearNonlinear": "plenoptic.models.LinearNonlinear",
    "plenoptic.simulate.models.frontend.LuminanceGainControl": "plenoptic.models.LuminanceGainControl",
    "plenoptic.simulate.LuminanceGainControl": "plenoptic.models.LuminanceGainControl",
    "plenoptic.simulate.models.frontend.LuminanceContrastGainControl": "plenoptic.models.LuminanceContrastGainControl",
    "plenoptic.simulate.LuminanceContrastGainControl": "plenoptic.models.LuminanceContrastGainControl",
    "plenoptic.simulate.models.frontend.OnOff": "plenoptic.models.OnOff",
    "plenoptic.simulate.OnOff": "plenoptic.models.OnOff",
    "plenoptic.simulate.models.naive.Identity": "plenoptic.models.Identity",
    "plenoptic.simulate.Identity": "plenoptic.models.Identity",
    "plenoptic.simulate.models.naive.Linear": "plenoptic.models.Linear",
    "plenoptic.simulate.Linear": "plenoptic.models.Linear",
    "plenoptic.simulate.models.naive.Gaussian": "plenoptic.models.Gaussian",
    "plenoptic.simulate.Gaussian": "plenoptic.models.Gaussian",
    "plenoptic.simulate.models.naive.CenterSurround": "plenoptic.models.CenterSurround",
    "plenoptic.simulate.CenterSurround": "plenoptic.models.CenterSurround",
    "plenoptic.metric.naive.mse": "plenoptic.metric.mse",
    "plenoptic.metric.model_metric.model_metric_factory": "plenoptic.metric.model_metric_factory",
    "plenoptic.metric.perceptual_distance.ssim": "plenoptic.metric.ssim",
    "plenoptic.metric.perceptual_distance.ms_ssim": "plenoptic.metric.ms_ssim",
    "plenoptic.metric.perceptual_distance.nlpd": "plenoptic.metric.nlpd",
    "plenoptic.metric.perceptual_distance.ssim_map": "plenoptic.metric.ssim_map",
    "plenoptic.metric.perceptual_distance.normalized_laplacian_pyramid": "plenoptic.metric.normalized_laplacian_pyramid",
    "plenoptic.simulate.canonical_computations.laplacian_pyramid.LaplacianPyramid": "plenoptic.process.LaplacianPyramid",
    "plenoptic.simulate.LaplacianPyramid": "plenoptic.process.LaplacianPyramid",
    "plenoptic.simulate.canonical_computations.steerable_pyramid_freq.SteerablePyramidFreq": "plenoptic.process.SteerablePyramidFreq",
    "plenoptic.simulate.SteerablePyramidFreq": "plenoptic.process.SteerablePyramidFreq",
    "plenoptic.simulate.canonical_computations.filters.circular_gaussian2d": "plenoptic.process.circular_gaussian2d",
    "plenoptic.simulate.circular_gaussian2d": "plenoptic.process.circular_gaussian2d",
    "plenoptic.tools.signal.rectangular_to_polar": "plenoptic.process.rectangular_to_polar",
    "plenoptic.tools.rectangular_to_polar": "plenoptic.process.rectangular_to_polar",
    "plenoptic.tools.signal.polar_to_rectangular": "plenoptic.process.polar_to_rectangular",
    "plenoptic.tools.polar_to_rectangular": "plenoptic.process.polar_to_rectangular",
    "plenoptic.simulate.canonical_computations.non_linearities.local_gain_control": "plenoptic.process.local_gain_control",
    "plenoptic.simulate.non_linearities.local_gain_control": "plenoptic.process.local_gain_control",
    "plenoptic.simulate.canonical_computations.non_linearities.local_gain_release": "plenoptic.process.local_gain_release",
    "plenoptic.simulate.non_linearities.local_gain_release": "plenoptic.process.local_gain_release",
    "plenoptic.simulate.canonical_computations.non_linearities.rectangular_to_polar_dict": "plenoptic.process.rectangular_to_polar_dict",
    "plenoptic.simulate.non_linearities.rectangular_to_polar_dict": "plenoptic.process.rectangular_to_polar_dict",
    "plenoptic.simulate.canonical_computations.non_linearities.polar_to_rectangular_dict": "plenoptic.process.polar_to_rectangular_dict",
    "plenoptic.simulate.non_linearities.polar_to_rectangular_dict": "plenoptic.process.polar_to_rectangular_dict",
    "plenoptic.simulate.canonical_computations.non_linearities.local_gain_control_dict": "plenoptic.process.local_gain_control_dict",
    "plenoptic.simulate.non_linearities.local_gain_control_dict": "plenoptic.process.local_gain_control_dict",
    "plenoptic.simulate.canonical_computations.non_linearities.local_gain_release_dict": "plenoptic.process.local_gain_release_dict",
    "plenoptic.simulate.non_linearities.local_gain_release_dict": "plenoptic.process.local_gain_release_dict",
    "plenoptic.tools.conv.correlate_downsample": "plenoptic.process.correlate_downsample",
    "plenoptic.tools.correlate_downsample": "plenoptic.process.correlate_downsample",
    "plenoptic.tools.conv.blur_downsample": "plenoptic.process.blur_downsample",
    "plenoptic.tools.blur_downsample": "plenoptic.process.blur_downsample",
    "plenoptic.tools.conv.upsample_convolve": "plenoptic.process.upsample_convolve",
    "plenoptic.tools.upsample_convolve": "plenoptic.process.upsample_convolve",
    "plenoptic.tools.conv.upsample_blur": "plenoptic.process.upsample_blur",
    "plenoptic.tools.upsample_blur": "plenoptic.process.upsample_blur",
    "plenoptic.tools.conv.same_padding": "plenoptic.process.same_padding",
    "plenoptic.tools.same_padding": "plenoptic.process.same_padding",
    "plenoptic.tools.signal.shrink": "plenoptic.process.shrink",
    "plenoptic.tools.shrink": "plenoptic.process.shrink",
    "plenoptic.tools.signal.expand": "plenoptic.process.expand",
    "plenoptic.tools.expand": "plenoptic.process.expand",
    "plenoptic.tools.signal.rescale": "plenoptic.process.rescale",
    "plenoptic.tools.rescale": "plenoptic.process.rescale",
    "plenoptic.tools.signal.add_noise": "plenoptic.process.add_noise",
    "plenoptic.tools.add_noise": "plenoptic.process.add_noise",
    "plenoptic.tools.signal.center_crop": "plenoptic.process.center_crop",
    "plenoptic.tools.center_crop": "plenoptic.process.center_crop",
    "plenoptic.tools.signal.modulate_phase": "plenoptic.process.modulate_phase",
    "plenoptic.tools.modulate_phase": "plenoptic.process.modulate_phase",
    "plenoptic.tools.signal.autocorrelation": "plenoptic.process.autocorrelation",
    "plenoptic.tools.autocorrelation": "plenoptic.process.autocorrelation",
    "plenoptic.tools.stats.variance": "plenoptic.process.variance",
    "plenoptic.tools.variance": "plenoptic.process.variance",
    "plenoptic.tools.stats.skew": "plenoptic.process.skew",
    "plenoptic.tools.skew": "plenoptic.process.skew",
    "plenoptic.tools.stats.kurtosis": "plenoptic.process.kurtosis",
    "plenoptic.tools.kurtosis": "plenoptic.process.kurtosis",
    "plenoptic.tools.data.to_numpy": "plenoptic.to_numpy",
    "plenoptic.tools.to_numpy": "plenoptic.to_numpy",
    "plenoptic.tools.data.convert_float_to_int": "plenoptic.convert_float_to_int",
    "plenoptic.tools.convert_float_to_int": "plenoptic.convert_float_to_int",
    "plenoptic.data.fetch.fetch_data": "plenoptic.data.fetch_data",
    "plenoptic.data.fetch.DOWNLOADABLE_FILES": "plenoptic.data.DOWNLOADABLE_FILES",
    "plenoptic.tools.data.make_disk": "plenoptic.data.disk",
    "plenoptic.tools.make_disk": "plenoptic.data.disk",
    "plenoptic.tools.data.polar_radius": "plenoptic.data.polar_radius",
    "plenoptic.tools.polar_radius": "plenoptic.data.polar_radius",
    "plenoptic.tools.data.polar_angle": "plenoptic.data.polar_angle",
    "plenoptic.tools.polar_angle": "plenoptic.data.polar_angle",
    "plenoptic.tools.data.load_images": "plenoptic.load_images",
    "plenoptic.tools.load_images": "plenoptic.load_images",
    "plenoptic.tools.validate.remove_grad": "plenoptic.remove_grad",
    "plenoptic.tools.remove_grad": "plenoptic.remove_grad",
    "plenoptic.tools.validate.validate_model": "plenoptic.validate.validate_model",
    "plenoptic.tools.validate_model": "plenoptic.validate.validate_model",
    "plenoptic.tools.validate.validate_input": "plenoptic.validate.validate_input",
    "plenoptic.tools.validate_input": "plenoptic.validate.validate_input",
    "plenoptic.tools.validate.validate_metric": "plenoptic.validate.validate_metric",
    "plenoptic.tools.validate_metric": "plenoptic.validate.validate_metric",
    "plenoptic.tools.validate.validate_coarse_to_fine": "plenoptic.validate.validate_coarse_to_fine",
    "plenoptic.tools.validate_coarse_to_fine": "plenoptic.validate.validate_coarse_to_fine",
    "plenoptic.tools.validate.validate_convert_tensor_dict": "plenoptic.validate.validate_convert_tensor_dict",
    "plenoptic.tools.validate_convert_tensor_dict": "plenoptic.validate.validate_convert_tensor_dict",
    "plenoptic.tools.optim.set_seed": "plenoptic.set_seed",
    "plenoptic.tools.set_seed": "plenoptic.set_seed",
    "plenoptic.tools.optim.mse": "plenoptic.loss.mse",
    "plenoptic.tools.mse": "plenoptic.loss.mse",
    "plenoptic.tools.optim.l2_norm": "plenoptic.loss.l2_norm",
    "plenoptic.tools.l2_norm": "plenoptic.loss.l2_norm",
    "plenoptic.tools.optim.relative_sse": "plenoptic.loss.relative_sse",
    "plenoptic.tools.relative_sse": "plenoptic.loss.relative_sse",
    "plenoptic.tools.optim.portilla_simoncelli_loss_factory": "plenoptic.loss.portilla_simoncelli_loss_factory",
    "plenoptic.tools.portilla_simoncelli_loss_factory": "plenoptic.loss.portilla_simoncelli_loss_factory",
    "plenoptic.tools.optim.groupwise_relative_l2_norm_factory": "plenoptic.loss.groupwise_relative_l2_norm_factory",
    "plenoptic.tools.groupwise_relative_l2_norm_factory": "plenoptic.loss.groupwise_relative_l2_norm_factory",
    "plenoptic.tools.optim.penalize_range": "plenoptic.regularize.penalize_range",
    "plenoptic.tools.regularization.penalize_range": "plenoptic.regularize.penalize_range",
    "plenoptic.tools.penalize_range": "plenoptic.regularize.penalize_range",
    "plenoptic.tools.io.examine_saved_synthesis": "plenoptic.io.examine_saved_synthesis",
    "plenoptic.tools.examine_saved_synthesis": "plenoptic.io.examine_saved_synthesis",
    "plenoptic.tools.external.plot_MAD_results": "plenoptic.external.plot_MAD_results",
    "plenoptic.tools.plot_MAD_results": "plenoptic.external.plot_MAD_results",
}

SYNTH_PLOT_FUNCS = {
    "plenoptic.synthesize.metamer.plot_loss": "plenoptic.plot.metamer_loss",
    "plenoptic.synthesize.metamer.display_metamer": "plenoptic.plot.metamer_imshow",
    "plenoptic.synthesize.metamer.plot_pixel_values": "plenoptic.plot.metamer_pixel_values",
    "plenoptic.synthesize.metamer.plot_representation_error": "plenoptic.plot.metamer_representation_error",
    "plenoptic.synthesize.metamer.plot_synthesis_status": "plenoptic.plot.metamer_synthesis_status",
    "plenoptic.synthesize.metamer.animate": "plenoptic.plot.metamer_animshow",
    "plenoptic.synthesize.mad_competition.display_mad_image": "plenoptic.plot.mad_imshow",
    "plenoptic.synthesize.mad_competition.display_mad_image_all": "plenoptic.plot.mad_imshow_all",
    "plenoptic.synthesize.mad_competition.plot_loss": "plenoptic.plot.mad_loss",
    "plenoptic.synthesize.mad_competition.plot_loss_all": "plenoptic.plot.mad_loss_all",
    "plenoptic.synthesize.mad_competition.plot_pixel_values": "plenoptic.plot.mad_pixel_values",
    "plenoptic.synthesize.mad_competition.plot_synthesis_status": "plenoptic.plot.mad_synthesis_status",
    "plenoptic.synthesize.mad_competition.animate": "plenoptic.plot.mad_animshow",
    "plenoptic.synthesize.eigendistortion.display_eigendistortion": "plenoptic.plot.eigendistortion_imshow",
    "plenoptic.synthesize.eigendistortion.display_eigendistortion_all": "plenoptic.plot.eigendistortion_imshow_all",
}

PLOT_FUNCS = {
    "plenoptic.tools.display.imshow": "plenoptic.plot.imshow",
    "plenoptic.tools.imshow": "plenoptic.plot.imshow",
    "plenoptic.imshow": "plenoptic.plot.imshow",
    "plenoptic.tools.display.animshow": "plenoptic.plot.animshow",
    "plenoptic.tools.animshow": "plenoptic.plot.animshow",
    "plenoptic.animshow": "plenoptic.plot.animshow",
    "plenoptic.tools.display.pyrshow": "plenoptic.plot.pyrshow",
    "plenoptic.tools.pyrshow": "plenoptic.plot.pyrshow",
    "plenoptic.pyrshow": "plenoptic.plot.pyrshow",
    "plenoptic.tools.display.plot_representation": "plenoptic.plot.plot_representation",
    "plenoptic.tools.plot_representation": "plenoptic.plot.plot_representation",
    "plenoptic.tools.display.clean_stem_plot": "plenoptic.plot.stem_plot",
    "plenoptic.tools.clean_stem_plot": "plenoptic.plot.stem_plot",
    "plenoptic.tools.display.update_plot": "plenoptic.plot.update_plot",
    "plenoptic.tools.update_plot": "plenoptic.plot.update_plot",
}

DEPRECATED = [
    "plenoptic.tools.display.clean_up_axes",
    "plenoptic.tools.clean_up_axes",
    "plenoptic.tools.display.rescale_ylim",
    "plenoptic.tools.rescale_ylim",
    "plenoptic.tools.display.update_stem",
    "plenoptic.tools.update_stem",
]
