name: build
on:
  workflow_dispatch:
  schedule:
  - cron: 0 0 * * 0     # weekly
  pull_request:
    branches:
    - main
# want pooch to raise an error if I've updated the file and forgot to update the
# hash.
env:
  POOCH_ALLOW_UPDATES: false

concurrency:
  # from https://stackoverflow.com/a/72408109/4659293
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  notebooks_cpu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
      fail-fast: false
    name: Execute notebooks
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 #v6.2.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: setup.py
    - name: Load cached FFmpeg
      id: cache-ffmpeg
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3

      with:
        path: |
          /usr/local/bin/ffmpeg
          /usr/local/bin/ffprobe
        key: ${{ runner.os }}-ffmpeg-5.1.1
    - name: Install FFmpeg if not cached
      if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
      run: |
        VERSION=6.0.1
        RELEASE_NAME=ffmpeg-${VERSION}-amd64-static
        wget --timeout=8 --tries=30 https://www.johnvansickle.com/ffmpeg/old-releases/${RELEASE_NAME}.tar.xz
        tar -xf ${RELEASE_NAME}.tar.xz
        mv ${RELEASE_NAME}/ffmpeg ${RELEASE_NAME}/ffprobe /usr/local/bin/
        rm -rf ${RELEASE_NAME}
    - name: Install dependencies
      run: |
        pip install --upgrade --upgrade-strategy eager .[nb] --extra-index-url https://download.pytorch.org/whl/cpu
    - name: Run notebooks
      run: |
        for file in $(find docs/ -name '*.md'); do
           # if it doesn't have this header, then it's not an executable notebook
           if [[ $(head -2 $file | tr '\n' ' ') == "--- jupytext: " ]]; then
               jupytext --execute $file
           fi
        done
  doctests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
      fail-fast: false
    name: Run doctests
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Install Python 3
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 #v6.2.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        # using the --upgrade and --upgrade-strategy eager flags ensures that
        # pip will always install the latest allowed version of all
        # dependencies, to make sure the cache doesn't go stale
        pip install --upgrade --upgrade-strategy eager .[test] --extra-index-url https://download.pytorch.org/whl/cpu
    - name: Run doctests with pytest
      run: |
        # 1. ignore warnings in doctests, since otherwise pytest fails.
        # 2. for some reason, much quicker when run in sequence (-n 0) rather
        #    than parallel.
        pytest -n 0 --doctest-modules src/ -W "ignore"
  check_sphinx_references:
    runs-on: ubuntu-latest
    name: Check sphinx references
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Install Python 3
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 #v6.2.0
      with:
        python-version: '3.12'
        cache: pip
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        # using the --upgrade and --upgrade-strategy eager flags ensures that
        # pip will always install the latest allowed version of all
        # dependencies, to make sure the cache doesn't go stale
        pip install --upgrade --upgrade-strategy eager .[docs] --extra-index-url https://download.pytorch.org/whl/cpu
    - name: Build docs (no notebooks)
      run: |
        # this is needed to create the sphinx obj.inv file
        make -C docs html O="-T"
        python linting/check_markdown.py docs/
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
      fail-fast: false
    name: Run pytest scripts
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Install Python 3
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 #v6.2.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        # using the --upgrade and --upgrade-strategy eager flags ensures that
        # pip will always install the latest allowed version of all
        # dependencies, to make sure the cache doesn't go stale
        pip install --upgrade --upgrade-strategy eager .[test] --extra-index-url https://download.pytorch.org/whl/cpu
    - name: Run tests with pytest
      run: |
        pytest --cov-report xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2

      with:
        token: ${{ secrets.CODECOV_TOKEN }}
  check_urls:
    runs-on: ubuntu-latest
    name: Check all urls are valid
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: urlstechie/urlchecker-action@b643b43e2ac605e1475331c7b67247d242b7dce4 # 0.0.34
      with:
        file_types: .md,.py,.rst
        print_all: false
        timeout: 5
        retry_count: 3

  check:
    if: always()
    needs:
    - notebooks_cpu
    - doctests
    - tests
    - check_urls
    - check_sphinx_references
    runs-on: ubuntu-latest
    steps:
    - name: Decide whether all tests and notebooks succeeded
      uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
      with:
        jobs: ${{ toJSON(needs) }}
